title: BabyPips for Android
description: Learn to trade Forex on the go, Offline.
show_downloads: true
theme: jekyll-theme-cayman
babypips:
  android_url: http://example.com/download.zip
  ios_url: another value
